name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: |
          10.0.x

    - name: Restore dependencies
      run: dotnet restore LinuxTracepoints-Net.sln

    - name: Build
      run: dotnet build LinuxTracepoints-Net.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test --solution LinuxTracepoints-Net.sln --configuration Release --verbosity normal
